### ISSUE TITLE
包安装问题

### ISSUE THREAD

**Issue by RealZark** [jxlwqq/id-validator#32]
通过 composer 安装，`data` 文件夹压根儿就没装。

**Comment by jxlwqq** [comment]
composer 安装一般在 vendor 目录，你修改过 composer 的镜像吗？一般安装失败都是这个问题。教程：https://laravel-china.org/wikis/16722

**Comment by RealZark** [comment]
![image](https://user-images.githubusercontent.com/16811858/46776014-63268200-cd3c-11e8-8e84-6f671bacdd96.png)
一直都是这个源。
![image](https://user-images.githubusercontent.com/16811858/46776057-8d783f80-cd3c-11e8-9902-4cb06fc0174c.png)
包是安装成功了的，就是少了 `data` 文件夹

**Comment by jxlwqq** [comment]
已修复，请更新到 1.4.12，谢谢反馈。
重新执行下命令即可：
```bash
composer require "jxlwqq/id-validator"
```
