### ISSUE TITLE
如果用户输入的身份证号码为“军官证123456”等含两个以上的汉字时，程序报错。

### ISSUE THREAD

**Issue by bing198619** [jxlwqq/id-validator#41]
报错信息如下所示：
PHP Fatal error:  Uncaught Error: Call to a member function format() on boolean in ...\jxlwqq\id-validator\src\Checker.php:111
Stack trace:
#0 ...\jxlwqq\id-validator\src\IdValidator.php(40): Jxlwqq\IdValidator\IdValidator->_checkBirthdayCode('19\xE8\xAF\x81144')
#1 test.php(8): Jxlwqq\IdValidator\IdValidator->isValid('\xE5\x86\x9B\xE5\xAE\x98\xE8\xAF\x81144125')
#2 {main}
  thrown in ...\jxlwqq\id-validator\src\Checker.php on line 111

**Comment by bing198619** [comment]
同样，如果身份证号码是"sssssssss123456"，也同样报错。

**Comment by jxlwqq** [comment]
本包不支持军官证。
