### ISSUE TITLE
地址码：数据更新至2019年08月

### ISSUE THREAD

**Issue by jxlwqq** [jxlwqq/id-validator#43]

**Comment by H122131986** [comment]
港澳台居住證號   找不到節點。
台灣台北市1978/10/10，18碼的，謝謝

**Comment by jxlwqq** [comment]
> 港澳台居住證號 找不到節點。
> 台灣台北市1978/10/10，18碼的，謝謝

有真实的号码吗？我这边测试一下。方便的话，可发我的邮箱 jxlwqq#gmail.com
