### ISSUE TITLE
代码里是不是应该去掉时间线的判断？

### ISSUE THREAD

**Issue by duantianyu** [jxlwqq/id-validator#53]
找到一身份证是 4110821989 开头的，地址是河南省长葛市。
但用这个插件获取到的河南省许昌市，看了下代码，是根据时间线判断了一下取值，导致没取到 411082 对应的长葛市
另外看 行政区划代码 http://www.mca.gov.cn/article/sj/xzqh/1980/?2  长葛市又的确是1995年新增上去的
代码里是不是应该去掉时间线的判断，只需要用最新的 行政区划代码 就可以了

**Comment by jxlwqq** [comment]
长葛市是中国河南省许昌市下辖的一个县级市。
所以没问题哈。

**Comment by duantianyu** [comment]
这个包的结果是："河南省" "许昌市 ""
用另外一个包 medz/id-card-of-china 取到的结果是："河南省" "许昌市" "长葛市"
感觉这样会更好些

**Comment by jxlwqq** [comment]
这个可能是1989年出生，但是在1995年之后才申报户口导致的，我看下怎么解决这个问题。

**Comment by duantianyu** [comment]
可以参考一下那个包，他取值是先取最新的，如果找不到，才从历史新增里取

**Comment by crabhw** [comment]
我这边也遇到了这个问题，比如重庆是97年启用50开头的编码，但是83年开始的重庆人好多就是50开头了。一是重庆在97年之前就提前启用了50开头的编码作为身份证号，但是区划编号没变。二是当时不少人16岁需要办身份证才去获得的身份证号。这种属于历史遗留原因吧。希望有个开关能关闭年份的判断。

**Comment by jxlwqq** [comment]
我加个参数，该参数默认为false，是否开启严格模式检查地址码和年份

**Comment by jxlwqq** [comment]
> 这个包的结果是："河南省" "许昌市 ""
> 用另外一个包 medz/id-card-of-china 取到的结果是："河南省" "许昌市" "长葛市"
> 感觉这样会更好些

已修复。

**Comment by jxlwqq** [comment]
> 我这边也遇到了这个问题，比如重庆是97年启用50开头的编码，但是83年开始的重庆人好多就是50开头了。一是重庆在97年之前就提前启用了50开头的编码作为身份证号，但是区划编号没变。二是当时不少人16岁需要办身份证才去获得的身份证号。这种属于历史遗留原因吧。希望有个开关能关闭年份的判断。

已修复。
