### ISSUE TITLE
重庆地区的身份证判断是不是有问题

### ISSUE THREAD

**Issue by zhuxiaojin** [jxlwqq/id-validator#57]
97年之前的都显示错误

**Comment by jxlwqq** [comment]
> 97年之前的都显示错误

发一些身份证例子，前十位即可。

**Comment by zhuxiaojin** [comment]
500226199605106232
500235198609155033

**Comment by jxlwqq** [comment]
> 500226199605106232
> 500235198609155033

测了下没问题，你安装的包的版本号是多少？更新到最新版试试？

**Comment by zhuxiaojin** [comment]
我的是1.4.23 更新到最新是OK的，感谢了

**Comment by jxlwqq** [comment]
> 我的是1.4.23 更新到最新是OK的，感谢了

不客气。
